### ISSUE TITLE
Can I use this program to make my own image retrieval system?

### ISSUE THREAD

**Issue by BerryRB** [toshi-k/kaggle-google-landmark-retrieval-2019#1]
Hi! Thanks for your sharing. I have not participated in this competition. Now I want to use this as my own retrieval system. How should I prepare my data?

**Comment by toshi-k** [comment]
Create directory under the input directory and put your training images.
If you want to evaluate your system like the competition, please create three directories like below.

* input
  * train
  * index
  * test
